// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPCpY3K3GIe_azM_kMy8CNX8KjpkpNz8',
    appId: '1:784893579307:web:9b4cf4838d719888519a6e',
    messagingSenderId: '784893579307',
    projectId: 'oceanissues-c563f',
    authDomain: 'oceanissues-c563f.firebaseapp.com',
    storageBucket: 'oceanissues-c563f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3pag3qUqmUZZG9oHm0Q0aaXkz5J0a458',
    appId: '1:784893579307:android:2787d3c406de299a519a6e',
    messagingSenderId: '784893579307',
    projectId: 'oceanissues-c563f',
    storageBucket: 'oceanissues-c563f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Y2swlR3JWEI6hxnrs8-XMPSlXuSDqf4',
    appId: '1:784893579307:ios:3cf371f41e50123e519a6e',
    messagingSenderId: '784893579307',
    projectId: 'oceanissues-c563f',
    storageBucket: 'oceanissues-c563f.appspot.com',
    iosClientId: '784893579307-6qehniq0efb2kshao9f2m7q6rrpdas76.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Y2swlR3JWEI6hxnrs8-XMPSlXuSDqf4',
    appId: '1:784893579307:ios:dac3caf2c0bfa421519a6e',
    messagingSenderId: '784893579307',
    projectId: 'oceanissues-c563f',
    storageBucket: 'oceanissues-c563f.appspot.com',
    iosClientId: '784893579307-55r57b54tda7n288fvped3jn1njnscvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocean.RunnerTests',
  );
}
